acrobot:
    max_history: 5    
    max_word_length: 12
    throttle_interval: 5
    keywords:
        - beer
        - sister
        - drunk
        - hash
model:
    name: CerebrasModel
    retries: 1
logging:
    level: INFO