acrobot:
    max_history: 5    
    max_word_length: 12
    throttle_interval: 5
    keywords:
        - beer
        - sister
        - drunk
        - hash
model:
    retries: 1
    use_config: user0
logging:
    level: INFO    
user0:
    provider: GeminiModel
    