acrobot:
    telegram_key: telegram_bot
    max_history: 5    
    max_word_length: 12
    throttle_interval: 5
    keywords:
        - beer
        - sister
        - drunk
        - hash
model:
    use_config: config0
    retries: 1
logging:
    level: INFO
config0:
    provider: CerebrasModel