acrobot:
    telegram_key: telegram_bot # Name of environment variable holding telegram API key.
    max_history: 5 # Max number of messages to retain in bot message context.
    max_word_length: 12 # Maximum allowed length of word to acronymize.
    throttle_interval: 5 # Delay in seconds between subsequent API requests (use to limit spamming).
    keywords: # These keywords will auto-trigger an acronym response.
        - beer
        - sister
        - drunk
        - hash
prompt:
    system: |
        You are in a hash house harriers chat group. You like sending creative, dirty acronyms inspired by the conversation.

        - The acronym words should form a proper sentence.
        - Relate your response to the conversation if possible.
        - Silly, outrageous, and raunchy responses are encouraged.
        - Answer in plain text only. Do not use any special formatting or markdown characters.
    user: |
        ### CONVERSATION ###
        {convo}

        Now generate an acronym for the word: "{word}". Reply with only the acronym.
model:
    use_config: config0 # This must match a configuration block below.
    retries: 1 # Number of LLM API retries in case of failure.
logging:
    level: INFO
# ***** List of model configurations *****
config0: #use default settings
    provider: CerebrasModel
    reasoning_effort: medium
config1: #use default settings
    provider: GeminiModel
    